#!/bin/bash
# Quick Reference: Environment Variables & API Endpoints
# Use this as a reference when configuring Render services

echo "📚 JanPukar Quick Reference"
echo "=============================="
echo ""

echo "## Environment Variables"
echo ""

echo "### Frontend (.env.local or Render env)"
echo "NEXT_PUBLIC_SUPABASE_URL = https://your-project.supabase.co"
echo "NEXT_PUBLIC_SUPABASE_ANON_KEY = eyJhbGciOiJIUzI1NiIsInR5cC..."
echo "NEXT_PUBLIC_SUPABASE_CLUSTER_ID = 00000000-0000-0000-0000-000000000000"
echo ""

echo "### Backend (.env or Render env)"
echo "SUPABASE_URL = https://your-project.supabase.co"
echo "SUPABASE_SERVICE_ROLE_KEY = eyJhbGciOiJIUzI1NiIsInR5cC... (SECRET!)"
echo "SUPABASE_CLUSTER_ID = 00000000-0000-0000-0000-000000000000"
echo "CORS_ALLOWED_ORIGINS = https://janpukar-frontend.onrender.com"
echo ""

echo "### Telegram Bot (.env or Render env)"
echo "TELEGRAM_BOT_TOKEN = 9999999999:AAE_PjM..."
echo "ADMIN_TELEGRAM_CHAT_IDS = 123456789,987654321"
echo "ADMIN_WEBHOOK_URLS = https://webhook.site/your-id"
echo "SMTP_HOST = smtp.gmail.com"
echo "SMTP_PORT = 587"
echo "SMTP_USER = your-email@gmail.com"
echo "SMTP_PASS = your-app-password (not your Gmail password!)"
echo "EMAIL_FROM = your-email@gmail.com"
echo ""

echo "## Backend API Endpoints"
echo ""

echo "### Health Checks"
echo "GET /health"
echo "  Response: {\"status\": \"ok\"}"
echo "  Purpose: Simple liveness check"
echo ""

echo "GET /health/ready"
echo "  Response: {\"status\": \"ok\", \"cluster_id\": \"...\"}"
echo "  Purpose: Readiness check with database connection"
echo ""

echo "### Grievances"
echo "GET /grievances"
echo "  Query: ?status=open&category=water"
echo "  Response: [{...}, {...}]"
echo "  Purpose: List grievances with filters"
echo ""

echo "POST /grievances"
echo "  Body: {\"title\": \"...\", \"latitude\": 28.5, \"longitude\": 77.2, ...}"
echo "  Response: {\"id\": \"...\", ...}"
echo "  Purpose: Create new grievance (requires auth)"
echo ""

echo "PATCH /grievances/{id}"
echo "  Body: {\"status\": \"in_progress\", \"updated_at\": \"...\"}"
echo "  Response: {\"id\": \"...\", ...}"
echo "  Purpose: Update grievance status (admin only)"
echo ""

echo "### Admin"
echo "POST /verify-admin"
echo "  Body: {\"telegram_chat_id\": 123456789}"
echo "  Response: {\"is_admin\": true/false}"
echo "  Purpose: Verify if user is admin"
echo ""

echo "## Frontend Pages"
echo ""

echo "GET /                                  Login page"
echo "GET /login                            Email/magic link auth"
echo "GET /submit                           Report grievance"
echo "GET /track                            View all grievances"
echo "GET /profile                          User profile + Telegram link"
echo "GET /admin                            Admin dashboard (requires auth)"
echo ""

echo "## Telegram Bot Commands"
echo ""

echo "/start                                Register and start bot interaction"
echo "/link                                 Get Telegram linking QR code"
echo "[Location share]                      Submit grievance with location"
echo ""

echo "## Important Notes"
echo ""

echo "⚠️  SUPABASE_SERVICE_ROLE_KEY is SECRET"
echo "   - Use it only on backend/bot servers"
echo "   - Never expose in frontend code or git"
echo "   - Never commit .env files"
echo ""

echo "⚠️  TELEGRAM_BOT_TOKEN is SECRET"
echo "   - Use it only in bot.py"
echo "   - Never expose in frontend"
echo "   - Never commit .env files"
echo ""

echo "⚠️  NEXT_PUBLIC_* variables are PUBLIC"
echo "   - These will be visible in browser"
echo "   - Only use for non-sensitive data"
echo "   - SUPABASE_ANON_KEY is intentionally public"
echo ""

echo "## Render Environment Setup"
echo ""

echo "1. Create web service for Frontend:"
echo "   - Runtime: Node"
echo "   - Build: npm install && npm run build"
echo "   - Start: npm run start"
echo "   - Add NEXT_PUBLIC_* variables"
echo ""

echo "2. Create web service for Backend:"
echo "   - Runtime: Python 3"
echo "   - Build: pip install -r requirements.txt"
echo "   - Start: uvicorn main:app --host 0.0.0.0 --port \$PORT"
echo "   - Add SUPABASE_* and CORS_ALLOWED_ORIGINS variables"
echo ""

echo "3. Create background worker for Telegram Bot:"
echo "   - Runtime: Python 3"
echo "   - Build: pip install -r requirements.txt"
echo "   - Start: python bot.py"
echo "   - Add TELEGRAM_BOT_TOKEN, SUPABASE_*, ADMIN_*, SMTP_* variables"
echo ""

echo "## Common Issues"
echo ""

echo "🔴 Backend returns 500 error:"
echo "   - Check SUPABASE_SERVICE_ROLE_KEY (use SR key, not anon)"
echo "   - Verify tables exist in Supabase"
echo "   - Check backend logs"
echo ""

echo "🔴 Bot doesn't respond to messages:"
echo "   - Check TELEGRAM_BOT_TOKEN is correct"
echo "   - Verify bot.py is running (check worker logs)"
echo "   - Ensure SUPABASE_SERVICE_ROLE_KEY is valid"
echo ""

echo "🔴 Frontend can't authenticate:"
echo "   - Verify SUPABASE_ANON_KEY is correct"
echo "   - Check Supabase Auth is enabled"
echo "   - Verify frontend .env variables are set"
echo ""

echo "## Getting Your Credentials"
echo ""

echo "📍 SUPABASE Credentials:"
echo "   1. Go to https://supabase.com/dashboard"
echo "   2. Select your project"
echo "   3. Go to Settings → API"
echo "   4. Copy Project URL (SUPABASE_URL)"
echo "   5. Copy 'anon public' key (SUPABASE_ANON_KEY)"
echo "   6. Copy 'service_role secret' key (SUPABASE_SERVICE_ROLE_KEY)"
echo ""

echo "🤖 TELEGRAM Bot Token:"
echo "   1. Message @BotFather on Telegram"
echo "   2. Type /newbot"
echo "   3. Follow the prompts"
echo "   4. Copy the token (format: 1234567:ABCDefGHIjKLmnoPQRStuvWXYz)"
echo ""

echo "🆔 ADMIN Chat ID:"
echo "   1. Message your bot with /start"
echo "   2. Check backend logs or Supabase profiles table"
echo "   3. Your chat ID is saved as telegram_chat_id"
echo ""

echo "💬 SMTP (optional, for email alerts):"
echo "   - Gmail: smtp.gmail.com:587"
echo "   - Generate App Password (not your Gmail password)"
echo "   - Enable 'Less secure app access' or use App Passwords"
echo ""

echo "=============================="
echo "Save this reference for later!"
echo ""
